FROM openjdk:17
COPY ./target/*.jar /shareus-gateway.jar
ENV TZ Asia/Shanghai
ENV LANG C.UTF-8
CMD ["-server.port=8080"]
EXPOSE 8080
ENTRYPOINT ["java","-jar","-Xms256m", "-Xmx256m","/shareus-gateway.jar"]