FROM openjdk:17
COPY ./target/*.jar /shareus-bot-web.jar
ENV TZ Asia/Shanghai
ENV LANG C.UTF-8
CMD ["-server.port=9997"]
EXPOSE 9997
ENTRYPOINT ["java","-jar","-Xms256m", "-Xmx256m","/shareus-bot-web.jar"]