FROM openjdk:17
COPY ./target/*.jar /shareus-system.jar
ENV TZ Asia/Shanghai
ENV LANG C.UTF-8
CMD ["-server.port=9201"]
EXPOSE 9201
ENTRYPOINT ["java","-jar","-Xms256m", "-Xmx256m","/shareus-system.jar"]