FROM openjdk:17
COPY ./target/*.jar /shareus-bot-robot.jar
ENV TZ Asia/Shanghai
ENV LANG C.UTF-8
CMD ["mkdir","/upload"]
CMD ["-server.port=9999"]
EXPOSE 9999
VOLUME ["/opt/download/mirai/groupFile//opt/download/mirai/groupFile/:/upload"]
ENTRYPOINT ["java","-Dmirai.slider.captcha.supported","-Dmirai.no-desktop=true","-jar","-Xms256m", "-Xmx256m","/shareus-bot-robot.jar"]
# java -Dmirai.slider.captcha.supported  -Dmirai.no-desktop=true -jar -Xms256m -Xmx256m  shareus-bot-robot.jar