FROM openjdk:17
COPY ./target/*.jar /shareus-visusal-monitor.jar
ENV TZ Asia/Shanghai
ENV LANG C.UTF-8
CMD ["-server.port=9100"]
EXPOSE 9100
ENTRYPOINT ["java","-jar","-Xms256m", "-Xmx256m","/shareus-visusal-monitor.jar"]